### Environment constants 

ARCH ?=
CROSS_COMPILE ?=
export

### general build targets

all:
	$(MAKE) all -e -C libloragw
	$(MAKE) all -e -C util_spi_stress

clean:
	$(MAKE) clean -e -C libloragw
	$(MAKE) clean -e -C util_spi_stress

### EOF
